### ISSUE TITLE
Fabric 1.20.1 not working

### ISSUE THREAD

**Issue by TheCyberQuake** [WiIIiam278/PAPIProxyBridge#154]
Similar to #78
Modrinth page says it should support Fabric versions 1.20.x, loading on 1.20.1 does not work

Error thrown:
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'PAPIProxyBridge' (papiproxybridge) 1.6.1 with any version that is compatible with:
		 - minecraft 1.20.1
More details:
	 - Mod 'PAPIProxyBridge' (papiproxybridge) 1.6.1 requires version 1.20.6 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:1.0.1]
	
Going back to 1.4.1, the version pushed to fix #78 gets it to load.

**Comment by WiIIiam278** [comment]
Hey so basically it's the case that the versions on Modrinth are just poorly labeled and I need to fix this. It's because I only distribute one jar file for all platforms and this jar supports paper 1.20.x (and older versions) but only the latest fabric version. It's annoying and on my list, but a distribution issue rather than a bug

**Comment by WiIIiam278** [comment]
Fixed in https://github.com/WiIIiam278/PAPIProxyBridge/commit/a848a9250024abb6c188f7b6b46e2447b87bf1dc, versions are now correctly labelled and split.
