### ISSUE TITLE
[Fabric 1.20.1] Crash with only Fabric API + PAPIProxyBridge + Text Placeholder API installed

### ISSUE THREAD

**Issue by unilock** [WiIIiam278/PAPIProxyBridge#78]
With only Fabric API, PAPIProxyBridge, and Text Placeholder API installed, the server crashes almost immediately upon startup.

<details>
<summary>Crash log</summary>
<br>

```
[wildstyle:~/D/velocity-test/fabric-1.20.1] unilock% ./start.sh
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[09:15:32] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[09:15:32] [main/INFO]: Loading 44 mods:
	- fabric-api 0.89.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.0+0883a8d477
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.20.1
	- papiproxybridge 1.4.1
	- placeholder-api 2.1.3+1.20.1
[09:15:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/unilock/Downloads/velocity-test/fabric-1.20.1/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[09:15:32] [main/INFO]: Compatibility level set to JAVA_16
[09:15:32] [main/INFO]: Compatibility level set to JAVA_17
[09:15:33] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath: [jar:file:/Users/unilock/Downloads/velocity-test/fabric-1.20.1/mods/PAPIProxyBridge-1.4.1.jar!/oshi.properties, jar:file:/Users/unilock/Downloads/velocity-test/fabric-1.20.1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.properties]
[09:15:33] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [jar:file:/Users/unilock/Downloads/velocity-test/fabric-1.20.1/mods/PAPIProxyBridge-1.4.1.jar!/oshi.architecture.properties, jar:file:/Users/unilock/Downloads/velocity-test/fabric-1.20.1/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties]
[09:15:33] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[PAPIProxyBridge-1.4.1.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.api.FabricLoader.getInstance(FabricLoader.java:41) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.minecraft.class_6396.mda5a7a3$fabric-crash-report-info-v1$lambda$fillSystemDetails$0$1(class_6396.java:544) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.handler$zzm000$fabric-crash-report-info-v1$fillSystemDetails(class_6396.java:541) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[PAPIProxyBridge-1.4.1.jar:?]
	... 3 more
Caused by: java.lang.IllegalStateException: trying to load net.fabricmc.loader.impl.FabricLoaderImpl from target class loader
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyNotInTargetCl(LoaderUtil.java:51) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.<clinit>(FabricLoaderImpl.java:578) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.api.FabricLoader.getInstance(FabricLoader.java:41) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.minecraft.class_6396.mda5a7a3$fabric-crash-report-info-v1$lambda$fillSystemDetails$0$1(class_6396.java:544) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.handler$zzm000$fabric-crash-report-info-v1$fillSystemDetails(class_6396.java:541) ~[server-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[PAPIProxyBridge-1.4.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[PAPIProxyBridge-1.4.1.jar:?]
	... 3 more
```
</details>

Versions:
- Minecraft `1.20.1`
- Fabric Loader `0.14.22`
- Fabric API `0.89.0+1.20.1`
- PAPIProxyBridge `1.4.1`
- Text Placeholder API `2.1.3+1.20.1`

**Comment by WiIIiam278** [comment]
_Should_ be fixed by https://github.com/WiIIiam278/PAPIProxyBridge/commit/5eaa49cfba1ada6a044de809ebafd22b16864818

Can you download this build (Click the "Plugin Jar" artifact on [this page](https://github.com/WiIIiam278/PAPIProxyBridge/actions/runs/6317729667)) and attempt to reproduce again?

**Comment by unilock** [comment]
That does appear to have fixed it, thanks!
